### ISSUE TITLE
EOL should be configurable

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#13]
[convo.js](https://github.com/codeforequity-at/testmybot/blob/master/testmybot/lib/convo.js#L96) uses OS specific EOL symbols.

This makes convo files less portable, because if I want to use the same convo files on Linux and on Windows I have to convert files to use correct EOL before running tests.

**Comment by codeforequity-at** [comment]
Portability is a good point, but another good point is the compatibility with text editors on different systems. Maybe implement some "auto-detect" when reading convo files.

**Comment by Naktibalda** [comment]
Do you really need to support Notepad?
All other editors on Windows can handle "\n".

An interesting side effect of using convo file with "\n" on Windows is that testmybot prints entire content of the file and marks test as passed without sending a single message.
It happens because entire content of the file is assigned to `testcase.name`.

**Comment by codeforequity-at** [comment]
Using \n as separator for now is a good solution. Approved pull request #16
