### ISSUE TITLE
Ability to run a single convo file

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#22]
It would be good to have a way to run a single convo file while developing a particular feature of the dialogue.
Mocha has `.only()` method.
Since convo is text only, I think that `only` could be prepended to a file suffix, e.g. `feature1.only.convo.txt`
`skip` could be implemented in a similar way.

**Comment by marines** [comment]
You would lose VC changes tracking doing so.

**Comment by Naktibalda** [comment]
a) .only won't be committed.
b) git is quite good at tracking renames.

**Comment by marines** [comment]
You won't be able to see what has changed without renaming it back to the original filename in the working tree.

**Comment by Naktibalda** [comment]
I just realized that I can use `node node_modules/mocha/bin/mocha spec --grep Complaint`
