### ISSUE TITLE
Split project to separate repos

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#34]
Currently you have 5 projects in one repository:

- [testmybot](https://github.com/codeforequity-at/testmybot/tree/master/testmybot)
- [testmybot-chat](https://github.com/codeforequity-at/testmybot/tree/master/testmybot-chat)
- [testmybot-fbmock](https://github.com/codeforequity-at/testmybot/tree/master/testmybot-fbmock)
- [testmybot-ide](https://github.com/codeforequity-at/testmybot/tree/master/testmybot-ide)
- [testmybot-slackmock](https://github.com/codeforequity-at/testmybot/tree/master/testmybot-slackmock)

The main problem with this approach is that it is impossible to install with npm from github.

For example, if this repository contained a single project with package.json at the top level,
it would be possible to install code from master branch by setting dependency to `"testmybot": "git+https://github.com/codeforequity-at/testmybot.git#master"`
and I would be able to install my branch containing the latest patch with `"testmybot": "git+https://github.com/Naktibalda/testmybot.git#fix-compatibility-with-botkit"` and so forth and so on.

But because it contains multiple projects, every time I want to install some patch, I have to publish a release of my fork on npm. 
And to actually consume my fork, I have to change package name in package.json of my app and in the source code of the my tests.
`"@naktibalda/testmybot": "^0.3.5",`
`const botkitHelper = require('@naktibalda/testmybot/helper/botkit');`

**Comment by codeforequity-at** [comment]
I know about this problem and this will be fixed for sure in near future.

**Comment by codeforequity-at** [comment]
Splitted it into seperate repositories

**Comment by Naktibalda** [comment]
Thanks
