### ISSUE TITLE
Cannot view container logs

### ISSUE THREAD

**Issue by srounce** [codeforequity-at/testmybot#44]
As of `1.0.0` I am unable to to view the STDOUT/STDERR (`console.log/error/...`) of my container with `docker logs -f` because the syslog driver is being used. Setting the `DEBUG=*` environment variable doesn't seem to show the output from the container either. 
How can I view the log output for the Syslog server or is there something else really obvious that I'm missing?

**Comment by codeforequity-at** [comment]
so enabling the DEBUG mode should show your container output.

The container output is logged to a file as well. You can set the Capabilities.CLEANUPTEMPDIR to false, then the working directory won't be deleted - you will find the log file in the latest working directory under botiumwork then.
