### ISSUE TITLE
Repeated bot answers after clicking the "Reset Chatbot" button

### ISSUE THREAD

**Issue by adrianaf** [codeforequity-at/testmybot#45]
I am recording a conversation with my facebook chatbot via fbDirect, but after clicking the "Reset Chatbot" button I get the same answer to my request twice. If I click another time the "Reset Chatbot" button I get the same answer to my request three times and so on.

I faced the same issue by clicking the "Clear Chat" button but I was able to solve it in that case by emptying the vm.messages array in the clearChat function:

`vm.clearChat = function() {
      vm.messages = [];
      vm.messages.length = 0;
    };`

I tried to do the same in the startDocker() function that, as far as I understand, is the one that is called when a you click on the "Reset Chatbot" button but it doesn't work and I'm not able to understand what could be the problem.

Can you help me?

Thank you.

**Comment by codeforequity-at** [comment]
This clearly is a bug.
You are using the browser emulator ?
Does is work in the console emulator ?

**Comment by adrianaf** [comment]
I'm using the browser emulator (I tried with both Firefox 57.0.4 and Chrome 63.0). 
I'm going to try the console emulator too and see if it works.

**Comment by codeforequity-at** [comment]
The emulators have been extracted to another project, [Botium CLI](https://github.com/codeforequity-at/botium-cli).
