### ISSUE TITLE
Test case failing due to :Error: No Mock online

### ISSUE THREAD

**Issue by kamrinkazi** [codeforequity-at/testmybot#51]
`kamrink@kamrink-ub:~/Desktop/Projects/orange_gassistant_bot$ npm test

> gassistant-bot@1.0.0 test /home/kamrink/Desktop/Projects/orange_gassistant_bot
> jasmine

Started
(node:21088) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: No Mock online
got Message: undefined
FF

Failures:
1) TestMyBot Sample Conversation Test Suite should answer to hello
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
`

**Comment by codeforequity-at** [comment]
TestMyBot seems to lack configuration. How does your testmybot.json look like ?

**Comment by kamrinkazi** [comment]
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "gassistant-bot",
      "FACEBOOK_API": true,
      "FACEBOOK_WEBHOOK_PORT": 3000,
      "FACEBOOK_WEBHOOK_PATH": "webhook",
      "CLEANUPTEMPDIR": false,
      "STARTCMD": "node index.js"
    },
    "Envs": {
      "NODE_TLS_REJECT_UNAUTHORIZED": 0,
      "NODE_ENV": "dev"
    }
  }
}

**Comment by kamrinkazi** [comment]
I have tried with both 5000,3000 port

**Comment by codeforequity-at** [comment]
Please enable logging ("export DEBUG=botium*,testmybot*") and attach the log output

**Comment by codeforequity-at** [comment]
Any news?
