### ISSUE TITLE
testmybot setup issue

### ISSUE THREAD

**Issue by sarvamariwala** [codeforequity-at/testmybot#52]
ENOENT: no such file or directory, open '/home/mtech/package.json'

**Comment by Naktibalda** [comment]
What steps have you done to get this error?
You did something seriously wrong.

**Comment by sarvamariwala** [comment]
$ git clone https://github.com/codeforequity-at/testmybot.git
$ cd testmybot/samples/facebook
$ npm install
$ npm test

**Comment by Naktibalda** [comment]
it looks like `cd testmybot/samples/facebook` step failed and you are still in your homedir.

**Comment by sarvamariwala** [comment]
Now, looks like this "npm WARN testmybot-sample1@1.0.0 No repository field." in stmybot/samples/facebook

**Comment by Naktibalda** [comment]
That's nothing to worry about.

**Comment by sarvamariwala** [comment]
thanks,
but, after the "sudo npm install" I wrote a command in terminal "npm test", it throw the error like:-
mtech@(username):~/testmybot/samples/facebook$ npm test

> testmybot-sample1@1.0.0 test /home/mtech/testmybot/samples/facebook
> jasmine

Started
(node:29638) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose failed: { Error: spawn docker-compose ENOENT\n    at exports._errnoException (util.js:1020:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)\n    at onErrorNT (internal/child_process.js:376:16)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)\n  code: \'ENOENT\',\n  errno: \'ENOENT\',\n  syscall: \'spawn docker-compose\',\n  path: \'docker-compose\',\n  spawnargs: \n   [ \'-p\',\n     \'testmybot-sample1\',\n     \'-f\',\n     \'/home/mtech/testmybot/samples/facebook/botiumwork/testmybot-sample1-20180207-155902-oC0j5/docker-compose.botium.yml\',\n     \'-f\',\n     \'/home/mtech/testmybot/samples/facebook/botiumwork/testmybot-sample1-20180207-155902-oC0j5/fbmock/docker-compose.fbmock.yml\',\n     \'-f\',\n     \'/home/mtech/testmybot/samples/facebook/botiumwork/testmybot-sample1-20180207-155902-oC0j5/docker-env.yml\',\n     \'build\' ] }\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:47:18)\n    at emitOne (events.js:96:13)\n    at ChildProcess.emit (events.js:188:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:217:12)\n    at onErrorNT (internal/child_process.js:376:16)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)'

what I will do next for this issue!!

**Comment by Naktibalda** [comment]
1. You don't need `sudo` to run `npm install`.
2. I will leave this docker issue to @codeforequity-at

**Comment by sarvamariwala** [comment]
ok, thanks @Naktibalda.

**Comment by codeforequity-at** [comment]
Did you install docker and docker-compose ? For this sample you need it ...

**Comment by sarvamariwala** [comment]
@codeforequity-at  when I installed "npm install"command on terminal, it return me "npm WARN testmybot-sample1@1.0.0 No repository field."

**Comment by sarvamariwala** [comment]
@codeforequity-at  Yes, I am installed docker and docker-compose.

**Comment by sarvamariwala** [comment]
Hi @codeforequity-at ,
when I wrote "npm test" on terminal,it gives me an error like :-

Started
(node:7139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:40:18)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:920:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)'


What I will do for same?

**Comment by codeforequity-at** [comment]
before running, please enable debug mode ("export DEBUG=botium*,testmybot*"). This should give more insights whats happening.

**Comment by sarvamariwala** [comment]
Hi @codeforequity-at,
before execute "npm test", enable debug mode it return like this:-

"botium-BotDriver BotDriver Build error: Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:40:18)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:920:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)' +2s
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:40:18)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:920:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)'
export DEBUG=botium*,testmybot*(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: container not available
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: container not available
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Error: container not available
F(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: container not available
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: container not available
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Error: container not available
F(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: container not available"

then, what should I do next??

**Comment by Naktibalda** [comment]
Try to run docker-compose manually and see what happens.

**Comment by codeforequity-at** [comment]
Agree, seems that docker-compose is not installed or not in the path.
You can add the docker compose path in your testmybot.json capabilities:

	  "DOCKERCOMPOSEPATH": "<absolute-path-to-docker-compose>"

More configuration possiblities are described here:
https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration

**Comment by sarvamariwala** [comment]
I tried but it gives same issue.

**Comment by codeforequity-at** [comment]
when you are running "docker-compose version" in command line, the docker-compose executable is found and some version information is shown ?

Also, there should be way more output when the debug mode is enabled. Did you run these two commands in a row ?

> export DEBUG=botium*,testmybot*
> npm test

**Comment by sarvamariwala** [comment]
Docker-compose version is 1.19.0.

**Comment by sarvamariwala** [comment]
when I execute command  "export DEBUG=botium*,testmybot*"   "npm test". It return like:- 

"npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "test"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! path /home/mtech/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/mtech/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/mtech/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mtech/npm-debug.log"

**Comment by sarvamariwala** [comment]
when I execute command "export DEBUG=botium*,testmybot*"  "npm test". It return like this :-

 botium-BotDriver BotDriver Build error: Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:40:18)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:920:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)' +2s
(node:4926) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (/home/mtech/testmybot/samples/facebook/node_modules/botium-core/src/helpers/ProcessUtils.js:40:18)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:920:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)'
(node:4926) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: container not available
(node:4926) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: container not available
(node:4926) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Error: container not available
F(node:4926) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: container not available

**Comment by codeforequity-at** [comment]
I have to admit that I have no idea what's going on there.
Can you please try another sample which doesn't require Docker, in "samples/watson" for example - just to make sure that this problem is related to docker.

It could be some kind of user permission problems, but its hard to do remote diagnosis here. Maybe it would be possible to grant temporary SSH access to your workstation, so I can analyse locally ? If yes, please don't post here, get in contact at hello@testmybot.com.
