### ISSUE TITLE
not able to run watson sample

### ISSUE THREAD

**Issue by hemachowdary** [codeforequity-at/testmybot#58]
Hi, 
I am using testmybot package to demonstrate chatbots testing. I am trying to execute watson sample. But somehow I am not able to make it up and running. Below are the steps followed:
1. Downloaded the project testmybot
2. Modified botium capaabilities in testmybot.json file located in watson folder
3. Modified "restaurant.convo.txt" under "testmybot\samples\watson\spec\convo" folder
4. inside watson directory i gave "npm install" followed by "npm test"
I am getting error. please find the attached error report.
![watsonbot](https://user-images.githubusercontent.com/2978192/36476062-c3522a9c-1722-11e8-8374-8262f203da2c.JPG)
Please let me know if I have missed out anything.

**Comment by codeforequity-at** [comment]
This is an NPM-related problem, not testmybot.
Please try to remove the "package-lock.json" file and the "node_modules" directory and run "npm install" again.

**Comment by hemachowdary** [comment]
I have watsonconversationservice bot.. for that I am using testmybot. To test my bot I have done the following changes 
1. changed the .convo.txt file located at "testmybot\samples\watson\spec\convo\restaurant.convo.txt" with my conversations 
2. added my watsonconversation details in testmybot.json file located at "testmybot\samples\watson\testmybot.json"
Is it sufficient or do I need to make any changes inorder to run the sample. Please correct me if I am wrong. 
Also could you please tell me the steps to test the watson sample. 
Thanks in advance

**Comment by codeforequity-at** [comment]
to run the sample you don't have to do anything else. just "npm install" / "npm test".

to use it with your own bot, of course you will have to change it.

**Comment by hemachowdary** [comment]
I am able to run the program after changing .convo.txt file with tescases specific to my bot. also I have changed testmybot.json with configurations specific to my watson bot. after changing all these i have done npm install followed by npm test. Below is the output that i got 
![testresults](https://user-images.githubusercontent.com/2978192/36519660-c487bef0-17b2-11e8-8eae-72aef8828038.JPG)
It is showing 0 failures. If i want to see the test results where can I find them. Is there a way to see the execution of the test cases step by step.

**Comment by codeforequity-at** [comment]
Well, that actually looks like it worked. When enabling debug mode, you will see more output:

https://github.com/codeforequity-at/botium-core/wiki/Troubleshooting

**Comment by hemachowdary** [comment]
it is working perfectly fine. Tested multiple scenarios. But why is not displaying the testcases in the console if all the test cases pass. only for failure cases it is displaying the messages.
![failurereport](https://user-images.githubusercontent.com/2978192/36523028-908b44f6-17c5-11e8-9c38-c4bbe46433f8.JPG)

**Comment by codeforequity-at** [comment]
well, testmybot itself is not a test runner. showing output is the job of a test runner like jasmine and mocha. most samples use jasmine. with command line parameters the output type can be configured. they can generate test output reports to be processed by a build server. and much more.

**Comment by codeforequity-at** [comment]
Botium is comparable to what Selenium/Appium are doing (unified API and "Page Object Model").
TestMyBot is a layer above Botium to integrate Botium with CI/CD pipelines and test runners like Mocha and Jasmine.

https://github.com/codeforequity-at/botium-core/wiki/What-is-Botium-%3F

**Comment by hemachowdary** [comment]
Does testmybot provides support for testing bots developed using[ kore.ai ](https://kore.ai/)
Can you please provide some inputs on this.

**Comment by codeforequity-at** [comment]
Currently supporting Watson and Dialogflow. Would be happy to get contact to someone from kore.ai to talk about integration.

**Comment by hemachowdary** [comment]
Hi could you please provide your email id so that we will help you in getting contact with the kore.ai team. We can have an email communication on this.

**Comment by codeforequity-at** [comment]
hello "at" testmybot.com

**Comment by hemachowdary** [comment]
ok thank you.. we will communicate with you over email.
