### ISSUE TITLE
every test cases are passing when using botkit with testmybot v1.2.3

### ISSUE THREAD

**Issue by nkkize** [codeforequity-at/testmybot#59]
I'm trying to run botkit with testmybot. But I found that every test cases are getting passed after the latest minior release (v1.2.3).

I figured out that inside `samples/botkit/jasmine` testmybot.json is missing. This file should contain below in order to validate negative test cases:
```
{
  "containermode": "local"
}
```
Please correct me if I am wrong.

**Comment by codeforequity-at** [comment]
the testmybot.json isn't required anymore. 

You mean, that there are test cases passing which actually should not succeed ?

**Comment by nkkize** [comment]
Yes. I changed bot responses in the bot.js without changing bot responses in *.convo.txt files. I also tried with changing bot responses in *.convo.txt file without changing bot responses in bot.js. In both the scenarios, all test cases are passing.

**Comment by nkkize** [comment]
on version 1.1.0, it is working fine. It's able to fail the negative test cases.

**Comment by codeforequity-at** [comment]
OK, there definitly was something screwed.
For the latest build 1.2.4 botkit integration should work again.

**Comment by codeforequity-at** [comment]
does it work ?

**Comment by nkkize** [comment]
yes. it worked. Thanks!
