### ISSUE TITLE
Is there any support for fb quick_reply?

### ISSUE THREAD

**Issue by kamrinkazi** [codeforequity-at/testmybot#61]
I tried quck_reply testcases and it is not comparing the quick replies

**Comment by codeforequity-at** [comment]
For features specific to a single platform, testmybot currently can be fed with JSON data to be sent/retrieved from the underlying channel. There is one sample doing a Facebook postback:

https://github.com/codeforequity-at/testmybot/blob/master/samples/facebook/spec/convo/should_answer_to_postback.convo.txt

**Comment by kamrinkazi** [comment]
I was trying to test this kind quick reply
https://developers.facebook.com/docs/messenger-platform/reference/send-api/quick-replies/

**Comment by kamrinkazi** [comment]
FB send message payload which I'm testing:
`curl -X POST -H "Content-Type: application/json" -d '{
  "recipient":{
    "id":"<PSID>"
  },
  "message":{
    **"text": "Here is a quick reply!",**
    "quick_replies":[
      {
        "content_type":"text",
        "title":"Search",
        "payload":"<POSTBACK_PAYLOAD>",
        "image_url":"http://example.com/img/red.png"
      },
      {
        "content_type":"location"
      }
    ]
  }
}' "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>"`

I observed that testmy bot is measuring the text part  **"text": "Here is a quick reply!",** only.

**Comment by kamrinkazi** [comment]
I have tried that also however getting below error.
Failures:
1) TestMyBot Test Suite for conversation pleasantries
  Message:
    Expected 'Here is a quick reply!' to contain undefined.

**Comment by codeforequity-at** [comment]
pls [enable logging](https://github.com/codeforequity-at/botium-core/wiki/Troubleshooting) and post the output here

**Comment by kamrinkazi** [comment]
Started
  botium-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-BotDriver   GITPATH: 'git',
  botium-BotDriver   GITBRANCH: 'master',
  botium-BotDriver   GITDIR: '.' } Capabilites: { PROJECTNAME: 'defaultproject',
  botium-BotDriver   TEMPDIR: 'botiumwork',
  botium-BotDriver   CLEANUPTEMPDIR: true,
  botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-BotDriver   CONTAINERMODE: 'inprocess',
  botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
  botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
  botium-BotDriver   DOCKERMACHINE: false,
  botium-BotDriver   DOCKERIMAGE: 'node:boron',
  botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
  botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
  botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
  botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  botium-BotDriver   WATSONCONVERSATION_URL: 'https://gateway.watsonplatform.net/conversation/api',
  botium-BotDriver   WATSONCONVERSATION_VERSION_DATE: '2017-05-26',
  botium-BotDriver   WATSONCONVERSATION_COPY_WORKSPACE: false,
  botium-BotDriver   WATSONCONVERSATION_USE_INTENT: false,
  botium-BotDriver   SIMPLEREST_METHOD: 'GET',
  botium-BotDriver   DIALOGFLOW_LANGUAGE_CODE: 'en-US',
  botium-BotDriver   DIALOGFLOW_USE_INTENT: false,
  botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
  botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
  botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
  botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
  botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
  botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-BotDriver   SCRIPTING_FORMAT: 'txt',
  botium-BotDriver   SCRIPTING_INPUT_TYPE: 'buffer' } +0ms
  botium-Convo About/Line 11: user says ConvoStep {
  botium-Convo   sender: 'me',
  botium-Convo   channel: null,
  botium-Convo   messageText: undefined,
  botium-Convo   sourceData: { postback: { payload: '{"intent":"m_about"}' } },
  botium-Convo   stepTag: 'Line 11' } +0ms
2018-03-06T15:36:53.477Z [info]: Received facebook webhook event with payload : {"sender":{"id":"me"},"recipient":{"id":1},"timestamp":1,"message":null,"postback":{"payload":"{\"intent\":\"m_about\"}"},"raw_message":{"sender":{"id":"me"},"recipient":{"id":1},"timestamp":1,"message":null,"postback":{"payload":"{\"intent\":\"m_about\"}"}},"_pipeline":{"stage":"receive"},"user":"me","channel":"me","page":1,"text":"{\"intent\":\"m_about\"}","payload":"{\"intent\":\"m_about\"}","type":"facebook_postback"}
  botium-Convo About wait for bot null +14ms
2018-03-06T15:36:53.545Z [info]: redis client connected and ready on host: 127.0.0.1 port: 6379
2018-03-06T15:36:53.554Z [info]: sending analytics to fb for inbound messages: {"_eventName":"manual_click","_button_payload":"{\"intent\":\"m_about\"}","_party_id":""}
2018-03-06T15:36:53.950Z [info]: sent analytics to fb successfully with event: {"_eventName":"manual_click","_button_payload":"{\"intent\":\"m_about\"}","_party_id":""}, fb res: "{\"error\":{\"message\":\"(#100) Param page_scoped_user_id must be a number\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"Fl4SVa9\\/13s\"}}"
2018-03-06T15:36:54.231Z [info]: fetching formatted message from template service
2018-03-06T15:36:54.231Z [info]: calling template service to get template by templateRef with request :{"template_ref":"ABOUT_TEMPLATE"}
2018-03-06T15:36:54.232Z [info]: attempting to call template service to get template by templateRef
2018-03-06T15:36:54.595Z [info]: sending push message: {"messaging_type":"RESPONSE","text":"I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.","channel":"me"}
2018-03-06T15:36:54.598Z [info]: sending push message: {"messaging_type":"RESPONSE","text":"More about me?","quick_replies":[{"content_type":"text","title":"Interests","payload":"{ \"intent\":\"m_interests\" }"},{"content_type":"text","title":"Skills","payload":"{ \"intent\":\"m_skills\" }"},{"content_type":"text","title":"Who Are You?","payload":"{ \"intent\":\"m_who_r_u\" }"}],"channel":"me"}
  botium-Convo About: bot says BotiumMockMessage {
  botium-Convo   sender: 'bot',
  botium-Convo   channel: 'default',
  botium-Convo   messageText: 'I\'m your 24/7 shopping assistant. Making your life easier, one purchase at a time.',
  botium-Convo   sourceData: undefined,
  botium-Convo   sourceAction: undefined } +1s
  botium-Convo About wait for bot null +1ms
  botium-Convo About: bot says BotiumMockMessage {
  botium-Convo   sender: 'bot',
  botium-Convo   channel: 'default',
  botium-Convo   messageText: 'More about me?',
  botium-Convo   sourceData: undefined,
  botium-Convo   sourceAction: undefined } +1ms
  botium-Convo About wait for bot null +0ms
2018-03-06T15:36:54.634Z [warn]: outbound message tracking failed user does not have a partyId associated for psid me
2018-03-06T15:36:54.640Z [warn]: outbound message tracking failed user does not have a partyId associated for psid me
2018-03-06T15:36:54.924Z [error]: failed to created subscription: messaging_vis_fbm for topic: messaging_vis_fbm error_message: 5 NOT_FOUND: Subscription topic does not exist stack: Error: 5 NOT_FOUND: Subscription topic does not exist
    at new createStatusError (/home/kamrink/Desktop/Projects/conversation/node_modules/grpc/src/client.js:65:15)
    at /home/kamrink/Desktop/Projects/conversation/node_modules/grpc/src/client.js:568:15
  botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at QueueTimeoutError (/home/kamrink/Desktop/Projects/conversation/node_modules/botium-core/src/helpers/QueueTimeoutError.js:3:5)
  botium-BaseContainer     at timeoutRequest (/home/kamrink/Desktop/Projects/conversation/node_modules/botium-core/src/helpers/Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (/home/kamrink/Desktop/Projects/conversation/node_modules/async/dist/async.js:4922:13)
  botium-BaseContainer     at ontimeout (timers.js:386:14)
  botium-BaseContainer     at tryOnTimeout (timers.js:250:5)
  botium-BaseContainer     at Timer.listOnTimeout (timers.js:214:5) +0ms
  botium-Convo About: bot says undefined +10s
FDEPRECATION: done callback received an Error object. Jasmine 3.0 will treat this as a failure


Failures:
1) TestMyBot Test Suite for conversation About
  Message:
    Failed: About/Line 39: bot says nothing
  Stack:
    Error: Failed: About/Line 39: bot says nothing
        at tmb.setupTestSuite (/home/kamrink/Desktop/Projects/conversation/node_modules/testmybot/src/helpers/jasmine.js:21:14)
        at container.WaitBotSays.then.err (/home/kamrink/Desktop/Projects/conversation/node_modules/botium-core/src/scripting/Convo.js:70:31)

1 spec, 1 failure
Finished in 11.254 seconds


Process finished with exit code 1

**Comment by codeforequity-at** [comment]
So, you are using the "inprocess" container model, did you use the BotkitHelper ? Or how do you connect your Bot code to Botium ?

**Comment by kamrinkazi** [comment]
Below is the code which I’m using to connect my bot code with testmybot:
I’m creating my bot controller first and then passing it in below code (using testmybot v1.2.4):
bot.helper.botkit().wireWithBotkit(controller);

**Comment by codeforequity-at** [comment]
So I'm sorry to tell you that this is a missing feature. The relevant source code is [here](https://github.com/codeforequity-at/testmybot/blob/master/src/helpers/botkit.js) - currently, postbacks are supported, but not quick replies

**Comment by kamrinkazi** [comment]
When can I expect this quick_reply feature to be supported?

**Comment by codeforequity-at** [comment]
Well, I am not sure if this really is the reason why your test case fails.
Everything looks fine:
* the m_about postback is sent to Botkit
* Botkit responds with two text messages ("I'm your shopping assistent ...." and "More about me?")

From the logfile it seems as if the convo is waiting for an additional text message from Botkit then, which isn't received, therefore failing.
Can you please post the full convo.txt file please.

**Comment by kamrinkazi** [comment]
#me
{
  "postback": {
    "payload": "{\"intent\":\"m_about\"}"
  }
}

#bot
I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.

#bot
More about me?

#bot
{
	"message": {
		"quick_replies": [
			{
				"content_type": "text",
				"title": "Interests",
				"payload": "{ \"intent\":\"m_interests\" }"
			},
			{
				"content_type": "text",
				"title": "Skills",
				"payload": "{ \"intent\":\"m_skills\" }"
			},
			{
				"content_type": "text",
				"title": "Who Are You?",
				"payload": "{ \"intent\":\"m_who_r_u\" }"
			}
		]
	}
}

**Comment by codeforequity-at** [comment]
The script is actually waiting for 3 messages from the bot, while there are only 2 - the quick replies are simply attached to the second message ("More about me?"). That's why the script is failing.

This script should actually work:

```
#me
{
  "postback": {
    "payload": "{"intent":"m_about"}"
  }
}

#bot
I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.

#bot
{
  "message": {
    "text":"More about me?",
    "quick_replies": [
    {
      "content_type": "text",
      "title": "Interests",
      "payload": "{ "intent":"m_interests" }"
    },
    {
      "content_type": "text",
      "title": "Skills",
      "payload": "{ "intent":"m_skills" }"
    },
    {
      "content_type": "text",
      "title": "Who Are You?",
      "payload": "{ "intent":"m_who_r_u" }"
    }
    ]
  }
}
```

**Comment by kamrinkazi** [comment]
There are only two sequences of the message.
I also tried with three sequences i.e More about me? as second message and remaining as third message.Then also it fails.

**Comment by codeforequity-at** [comment]
So, can you confirm that this script works ?
It is the same as yours from above, but the quick replies are actually not validated at all.

```
#me
{
  "postback": {
    "payload": "{"intent":"m_about"}"
  }
}

#bot
I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.

#bot
More about me?
```

**Comment by kamrinkazi** [comment]
Yes ,that gets passed

**Comment by nkkize** [comment]
Looking into the same thing. Can you please confirm if its an issue?

**Comment by codeforequity-at** [comment]
@kamrinkazi and the sample I posted above, where I merged the "More about me?" text with the quick replies ? It doesn't work ? is there another error message now ?

**Comment by kamrinkazi** [comment]
when I try only text, spec gets passed.
```
#me
{
  "postback": {
    "payload": "{"intent":"m_about"}"
  }
}

#bot
I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.

#bot
More about me?
```
But when I try text with quick_replies,spec gets failed.

```
#me
{
  "postback": {
    "payload": "{"intent":"m_about"}"
  }
}

#bot
I'm your 24/7 shopping assistant. Making your life easier, one purchase at a time.

#bot
{
  "message": {
    "text":"More about me?",
    "quick_replies": [
    {
      "content_type": "text",
      "title": "Interests",
      "payload": "{ "intent":"m_interests" }"
    },
    {
      "content_type": "text",
      "title": "Skills",
      "payload": "{ "intent":"m_skills" }"
    },
    {
      "content_type": "text",
      "title": "Who Are You?",
      "payload": "{ "intent":"m_who_r_u" }"
    }
    ]
  }
}
```
**Error message I have already posted above.**

**Comment by kamrinkazi** [comment]
Any updates?

**Comment by codeforequity-at** [comment]
Currently working on some test cases for using Botkit with quick replies. I am still not sure what causes the error, because when running a similar test case it works for me (one of my favourite excuses from developers ...).

**Comment by kamrinkazi** [comment]
Yes above sample is working.
however my test cases are getting passed in all scenarios like failed test cases are also getting passed.

**Comment by codeforequity-at** [comment]
One source of the problem could be that for the latest builds you shouldn't pass in any jasmine functions as matcher anymore, as they are way to inflexible. While it is still possible to inject custom matcher functions, it is not possible to use the standard jasmine asserts anymore. The matching behaviour can be changed with the capability "SCRIPTING_MATCHING_MODE" (in testmybot.json - regexp, include, includeLowerCase, equals).

**Comment by codeforequity-at** [comment]
Did you test it ?

**Comment by kamrinkazi** [comment]
Yes , It worked. Thanks
