### ISSUE TITLE
Test cases are passed even if I don't pass anything in expected result

### ISSUE THREAD

**Issue by kamrinkazi** [codeforequity-at/testmybot#62]
- Test cases get passed even if I don't pass anything in expected.

Example 1:
```
#me
hi

#bot
```

- Test cases get passed even if it partially match with the expected result
Example 2:
Expected result for  **Hi** is **Hi There**,Now if I put Only **Hi** in expected result then also it gets passed.It only fails when I put invalid thing,then it gets failed,e.g **Hi K** instead of **Hi there**
```
#me
Hi

#bot
Hi 
```

**Comment by codeforequity-at** [comment]
By default, pattern matching is used for verification.

**Comment by kamrinkazi** [comment]
What if I don't pass anything in expected result?
#me
hi

#bot

**Comment by codeforequity-at** [comment]
This is a placeholder for everything (could use a "*" as well).

**Comment by codeforequity-at** [comment]
maybe same reason as #61 ?

**Comment by codeforequity-at** [comment]
?

**Comment by codeforequity-at** [comment]
closed for inactivity
