### ISSUE TITLE
Failed to install fbdirect example

### ISSUE THREAD

**Issue by lzmartinico** [codeforequity-at/testmybot#66]
When trying `npm install` on the _fbdirect_ example on a MacOS machine running Node@5.6.0, installation fails with error:

```
npm WARN testmybot-sample-monitoring@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: acorn@3.3.0 (node_modules/testmybot/node_modules/acorn-jsx/node_modules/acorn):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '$HOME/testmybot/node_modules/acorn-jsx/node_modules/acorn' -> '$HOME/testmybot/node_modules/acorn-jsx/node_modules/.acorn.DELETE'

npm ERR! path $HOME/testmybot/node_modules/body-parser/node_modules/ms
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '$HOME/testmybot/node_modules/body-parser/node_modules/ms' -> '$HOME/testmybot/node_modules/body-parser/node_modules/.ms.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by codeforequity-at** [comment]
please delete the "packages-lock.json" and the node_modules folder and run
npm install again.

by the way, I think testmybot won't work on Node 5.6.0 - if you are
receiving strange "syntax error" messages when running it you will have to
upgrade Node.

**Comment by lzmartinico** [comment]
Thanks that fixed it - and I have upgraded my Node build as well. However, when I try to run a test case,  it terminates successfully after one exchange between me and the bot, with my second message never been sent. I also get warning `DEPRECATION: done callback received an Error object. Jasmine 3.0 will treat this as a failure` as soon as I start the test

**Comment by codeforequity-at** [comment]
try to enable logging and run again:
`export DEBUG=botium*`

the "fbdirect" mode is pretty unstable - it relies on a 3rd party library which is not officially supported by facebook, therefore it is broken very often.

The Jasmine message can be ignored.
