### ISSUE TITLE
npm run emulator throws error

### ISSUE THREAD

**Issue by jawad360** [codeforequity-at/testmybot#72]
On running command 'npm run emulator' it throws an error 'missing script: emulator'

**Comment by codeforequity-at** [comment]
please give a little more context - what did you do before ?

**Comment by jawad360** [comment]
Hi 

Thanks for the quick reply.
I simple clone the git.
Then as per wiki:
'npm install' in the root directory.
'npm run emulator'

After this I'm getting this error

Thanks

**Comment by codeforequity-at** [comment]
Well, the emulator target is only available for the samples - look at the package.json file in the folder of the sample you are trying to run. what sample are we talking about here ?

**Comment by jawad360** [comment]
Ok got it
Thanks a lot
