### ISSUE TITLE
readConvos error: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by ikr0m** [codeforequity-at/testmybot#74]
This error appears when I run like this:
 **testmybot-master/samples/watson$ npm run emulatorBrowser**

> readConvos error: TypeError: Converting circular structure to JSON

I found which place throws error:

**/samples/watson/node_modules/testmybot/src/emulator/browser/index.js**

```javascript
  router.route('/testcases')
    .post(function(req, res) {
      if (!req.body.header || !req.body.header.name)
        return res.json({ success: false, error: 'Name not specified' });
      if (!req.body.conversation)
        return res.json({ success: false, error: 'Conversation not specified' });

      try {
        const filename = tmb.convoReader.writeConvo(req.body, true);
        return res.json({ success: true, filename: filename });
      } catch (err) {
        console.log('writeConvo error: ' + err);
        return res.json({ success: false, error: err });
      }
    }).get(function(req, res) {
      try {
        const convos = tmb.convoReader.readConvos()
        return res.json(convos);  // <---- This line says "TypeError: Converting circular structure to JSON"
      } catch (err) {        
        console.log('readConvos error: ' + err);
        return res.json({ success: false, error: err });
      }
    });
```

I've logged *convos* value before throwing error, this is *convos*'s value:
```javascript
[ Convo {
    provider: 
     ScriptingProvider {
       caps: [Object],
       compilers: [Object],
       convos: [Circular],
       utterances: {},
       match: [Function],
       scriptingEvents: [Object] },
    header: ConvoHeader { name: 'testt_1', order: 1, description: undefined },
    conversation: [ [Object], [Object], [Object], [Object] ],
    sourceTag: 'testt_1.convo.txt' },
  Convo {
    provider: 
     ScriptingProvider {
       caps: [Object],
       compilers: [Object],
       convos: [Circular],
       utterances: {},
       match: [Function],
       scriptingEvents: [Object] },
    header: ConvoHeader { name: 'testt_2', order: 2, description: undefined },
    conversation: 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    sourceTag: 'testt_2.convo.txt' } ]
```

**>npm run emulator** works fine, only **>npm run emulatorBrowser** throws above error. Browser opens http://127.0.0.1:3000/#!/testsuite but there is nothing to do there, busy loader rotates.
I'm using nodejs v6.9.5, npm 3.10.10, kubuntu 16.04

**Comment by ikr0m** [comment]
Thanks for quick response. Should I create this excel spreadsheet manually? I'm using IBM Watson chatbot.

**Comment by ikr0m** [comment]
That's good. 
I wanted to create new issue about new feature but let me know your opinion first.
I expected/imagined that **TestByBot** will generate test cases and use them in testing. In this case I don't create test cases manually (by chatting in console or in excel file).
Details: currently I'm using IBM Watson. It's workspace contains many intents, entities, dialogs. Let's call it ws_v1. I've tested it well (and I want to keep this version's state). In future I'll add new intents, entities, dialogs to ws_v1. Let's call it ws_v2.  And I want to know if there is regression in ws_v2. I want to apply ws_v1 test cases to ws_v2. In this case I can find what is broken in ws_v2 after changes.
How: I've got workspace exported json file. It contains intents, entities, dialogs. If we can create test cases from this json, it would be great. Otherwise I've to create test cases manually from [IBM Watson](https://watson-assistant.ng.bluemix.net/ )'s site.
So my question, is it possible to generate test cases from workspace json file or using IBM Watson's API? It's ok if it can't generate all possible test cases. It can be reviewed and added manually.

**Comment by codeforequity-at** [comment]
We are using it in exactly the way you described in one of our projects.

There is a new repository available called "botium-cli" which provides test case generators for such scenarios (or better to say: will provide): https://github.com/codeforequity-at/botium-cli - its fully undocumented right now, but it contains a command line help and could be useful to you:

One of the currently included functionality is to generated test cases from IBM Watson Intents and User Examples: for each intent in your workspace, it will look up all trained user examples and generate one test case for each user example, checking if the user example resolves to the given intent. We are using it for regression testing right now, to identify problems with failed user input training.
Generating test cases from conversation nodes would be the next step.

Your testmybot.json should look like this:

```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "whatever",
      "CONTAINERMODE": "watsonconversation",
      "WATSONCONVERSATION_USER": "...",
      "WATSONCONVERSATION_PASSWORD": "...",
      "WATSONCONVERSATION_WORKSPACE_ID": "...",
      "WATSONCONVERSATION_USE_INTENT": true // this is important
    }
  }
}
```

then the steps would be:

```
> npm install -g botium-cli
> botium-cli import watson-intents --config path/to/testmybot.json
```

**Comment by codeforequity-at** [comment]
```
>botium-cli run --config path/to/testmybot.json --convos path/to/your/convo/files
```

**Comment by ikr0m** [comment]
`"WATSONCONVERSATION_USE_INTENT": true` param was very important in testmybot.json. Without it, it produces many errors. 
**botium-cli** is very powerful tool. I've already found 2 conflicts in my workspace. There were same examples in different intents.
I'll expect more features like creating test cases, testing entities, dialogs from botuim-cli. So far I'll create test cases manually from console with testmybot.
Thank you!

**Comment by codeforequity-at** [comment]
emulator can be run from botium-cli as well:

```
>botium-cli emulator
```

**Comment by codeforequity-at** [comment]
Added the browser emulator to the botium-cli as well.
