### ISSUE TITLE
FbDirect : Converting circular structure to JSON

### ISSUE THREAD

**Issue by jawad360** [codeforequity-at/testmybot#75]
When running fbDirect project in emulatorBrowser im getting issue as 'TypeError: Converting circular structure to JSON' in my CMD.
Seems like /src/emulator/browser/index.js is failing on line 121 while stringify an array of object.
'convos' is as Array class 'Convo' which is not able to stringify

**Comment by ikr0m** [comment]
This issue has been reported already. Please refer to https://github.com/codeforequity-at/testmybot/issues/74
