### ISSUE TITLE
files watcher and auto reload when using testmybot_ide

### ISSUE THREAD

**Issue by anasAsh** [codeforequity-at/testmybot#8]
am using testmybot IDE for local testing on a facebook bot, it is very annoying to reload docker containers on code changes while developing.
I would like to discuss with you what changes do you think we will need if we want to implement auto reload mechanism for the node server inside testmybot container on files updates?

**Comment by codeforequity-at** [comment]
Docker should be clever enough to cache the container images. Its very important to always have an absolutly clean environment for each test case. What are your concerns ? Is it about the delay when running the test cases ?

**Comment by codeforequity-at** [comment]
I'm thinking about adding something to update the files within the container without stopping it. technically this would be rather easy (adding an FTP service to the docker container). During development, this could be really helpful, you are right.

**Comment by anasAsh** [comment]
so far what i did is that i added my own `Dockerfile.testmybot` and linked it via the configurations.
where i removed COPY and added PM2 as a dependency.
```
FROM node:boron
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY ./package.json /usr/src/app/
RUN npm install --production
RUN npm install pm2 -g
CMD pm2-docker start docker-process.json --no-daemon
```

and was trying to load the files as a `VOLUME` instead of using `COPY`
`
docker run -v /PATH/TO/MY/PROJECT:/usr/src/app -d -e NODE_TLS_REJECT_UNAUTHORIZED=0 --name testmybot --network testmybot_network --network-alias testmybot testmybot
`
this worked, but i didn't yet done many tests on it and it will need some changes on `testMyBot`, the goal here is to suppoer using `testMyBot` for development, where developers can use testMyBot_ide to see the results of their changes instantly.

**Comment by anasAsh** [comment]
the FTP would do it as well, but we will still need to run the application with a watcher to restart on code updates.

**Comment by anasAsh** [comment]
here are the contents of `docker-process.json`
```
{
  "apps": [{
    "name": "facebook-bot",
    "script": "facebook/app.js",
    "instances": "1",
    "exec_mode": "cluster",
    "watch": true,
    "watch_options": {
      "usePolling": true
    },
    "ignore_watch" : ["node_modules/*"],
    "env": {
      "NODE_ENV": "development",
      "PORT": 5000,
    }
  }]
}
```

**Comment by codeforequity-at** [comment]
very cool, I will try to make this work in my environment, thanks for your input!

**Comment by anasAsh** [comment]
the command above is working normally from command line, but returns error code 125 from testmybot, it might be an issue in my machine, but in general i think this should work.

**Comment by anasAsh** [comment]
btw, added a new configurations param to testmybot called `volume`: `path/to/project/on/host/:path/on/container`

I don't really like this, do you think there is any other way to add the volume path?

here is the commit
https://github.com/anasAsh/testmybot/commit/77994b07a4e303e8cddf3f9093980e98d0e9f405

**Comment by codeforequity-at** [comment]
hi, with the latest commit we decided to use docker's volume mounting feature to shorten the load time. The project directory is just mounted as /usr/src/app within the docker container. it's now loading way faster (within seconds), this approach seems to work very well.

Many thanks for your input on this!
