### ISSUE TITLE
How to run single test?

### ISSUE THREAD

**Issue by ikr0m** [codeforequity-at/testmybot#95]
Now I'm running all tests like `npm run test`
How can I run single test (single file?

**Comment by codeforequity-at** [comment]
Single files are not possible, but single directories.
See this sample: https://github.com/codeforequity-at/testmybot/tree/master/samples/utterances

spec-folder contains three spec.js files, each pointing to another directory, starting jest pointing to just one of the files will run only testcases from single directory.

the sample is for jest, but can be easily adapted to mocha.

**Comment by Naktibalda** [comment]
You could use `--grep` parameter of mocha:
`node node_modules/mocha/bin/mocha spec/ --exit --grep=name-fragment`
More about grep: http://www.petecorey.com/blog/2016/07/25/mochas-grep-flag/

**Comment by codeforequity-at** [comment]
Nice hint!

**Comment by codeforequity-at** [comment]
@ikr0m is this something you could use for your scenario ?

**Comment by ikr0m** [comment]
@Naktibalda @codeforequity-at Thank you guys, it works great!
I've run above command in samples/watson folder.
Small issue that mochawesome-report is not updated with last run test results. I can see test results in terminal. So far this is ok.
